services:
  postgres:
    image: postgres:13
    container_name: devops-postgres
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - devops-network

  redis:
    image: redis:latest
    container_name: devops-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
    container_name: devops-elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es-data:/usr/share/elasticsearch/data

volumes:
  postgres-data:
  redis-data:
  es-data:

networks:
  devops-network:
    name: devops-network
    external: true
